import { Octokit } from "@octokit/rest";
import "dotenv/config";

const github = new Octokit({
    auth: process.env.GITHUB_TOKEN,
});

export interface FixDeployment {
    owner: string;
    repo: string;
    pull_number: number;
    baseBranch: string;
    fixedFiles: Array<{ path: string; content: string }>;
}

export async function deployAutonomousFix(deploy: FixDeployment): Promise<string> {
    const { owner, repo, pull_number, baseBranch, fixedFiles } = deploy;
    
    console.log(`[PUSHER] 🚀 Deploying autonomous fix for ${owner}/${repo} PR #${pull_number}...`);

    try {
        // 1. Create a unique branch name
        const newBranch = `antigravity-fix-pr-${pull_number}-${Date.now()}`;
        
        // 2. Get the SHA of the base branch
        const { data: refData } = await github.git.getRef({
            owner,
            repo,
            ref: `heads/${baseBranch}`,
        });
        const baseSha = refData.object.sha;

        // 3. Create the new branch
        await github.git.createRef({
            owner,
            repo,
            ref: `refs/heads/${newBranch}`,
            sha: baseSha,
        });
        console.log(`[PUSHER] Branch created: ${newBranch}`);

        // 4. Push each fixed file
        for (const file of fixedFiles) {
            // We need the file's current SHA to update it
            let fileSha;
            try {
                const { data: fileData } = await github.repos.getContent({
                    owner,
                    repo,
                    path: file.path,
                    ref: newBranch
                });
                if (!Array.isArray(fileData)) {
                    fileSha = fileData.sha;
                }
            } catch (e) {
                // File might be new, no SHA needed
            }

            await github.repos.createOrUpdateFileContents({
                owner,
                repo,
                path: file.path,
                message: `🤖 AI Fix: Resolved vulnerabilities/bugs verified by Sandbox`,
                content: Buffer.from(file.content).toString("base64"),
                branch: newBranch,
                sha: fileSha
            });
            console.log(`[PUSHER] Pushed fix for: ${file.path}`);
        }

        // 5. Create the PR
        const { data: newPR } = await github.pulls.create({
            owner,
            repo,
            title: `🤖 [AI FIX] Automated Patch for PR #${pull_number}`,
            head: newBranch,
            base: baseBranch,
            body: `This is an **Automated Fix Pull Request** generated by Antigravity AI.
            
### 🛠️ Changes Breakdown
The AI Auditor identified critical issues in PR #${pull_number}. This PR contains a verified patch that passed all Sandbox technical tests.

### ✅ Verification
- **Vulnerability Patching**: Verified via Ralph-Loop simulation.
- **Logic Integrity**: Maintained.
- **Tests Passed**: YES.

_Review and merge to resolve the identified vulnerabilities._`
        });

        console.log(`[PUSHER] ✅ Autonomous PR Created: ${newPR.html_url}`);
        return newPR.html_url;

    } catch (error: any) {
        console.error(`[PUSHER] ❌ Failed to deploy fix: ${error.message}`);
        throw error;
    }
}
